### ISSUE TITLE
Post Rules not displayed

### ISSUE THREAD

**Issue by tslee188** [PaloAltoNetworks/pan-os-python#222]
## Documentation link
examples/ensure_security_rule.py

Does not display post rules, only local rules are displayed

## Describe the problem
I have post-rule that was pushed by panorama to the firewall, but the script does not return post rule when ensure_security_rule.py was run, was it the intend ?
rulebase = pandevice.policies.Rulebase()
fw.add(rulebase)
current_security_rules = pandevice.policies.SecurityRule.refreshall(
rulebase)

I tried changing the following and it does not help as well.
rulebase = pandevice.policies.Rulebase() --> rulebase = pandevice.policies.PostRulebase()

**Comment by shinmog** [comment]
@tslee188 

This is the correct behavior.

Rules coming from Panorama pre-rulebase / post-rulebase are stored at a completely different XPATH in PAN-OS.  The XPATH and objects retrieved when executing the code in the opening comment will be all rules locally defined in the given vsys (vsys1 if not specified).

If you need to be able to retrieve this information from the firewall, please rename this issue appropriately, otherwise it should be ok to close this issue.
