### ISSUE TITLE
create_similar() for Address Groups creates objects in Pano but they cannot be added to Security Pre-Rules

### ISSUE THREAD

**Issue by aaronmelton** [PaloAltoNetworks/pan-os-python#269]
## Describe the bug

When using the create_similar() function to create Dynamic Address Groups (using 'dynamic_value' to assign tags), these objects are created in Panorama but are not available on the pick-list to add as a Source or Destination to a Security Pre-Rule.  I can confirm the creation of these Address Groups from the Objects tab.  However, they do not appear as a selection to be used on existing or new Security Pre-Rules.  Restarting the management services on Panorama via the CLI will cause these Address Groups to be available as a Source or Destination on a Security Pre-Rule.

## Expected behavior

The Address Group object created through the create_similar() function should appear as an object available for use on a Security Pre-Rule.

## Current behavior

The Address Group object created through the create_similar() function are not available for use, although they appear in the configuration of Panorama, unless the management services on Panorama are restarted.

## Steps to reproduce

```
group_object = AddressGroup(name="Address Group 1", dynamic_value="'A Dynamic Tag'", tag=["A_Static_Tag"])
first_group = group_object
active_pano.add(group_object)
group_object = AddressGroup(name="Address Group 2", dynamic_value="'Another Dynamic Tag'", tag=["A_Static_Tag"])
active_pano.add(group_object)
active_pano.find(first_group).create_similar()
```

Where 'active_pano' is a function that returns the Active Panorama in an HA pair.

The major difference between the code snippet above and my actual code is that I capture the very first Address Group name I create (as 'first_group') and loop through multiple groups which are added using 'active_pano.add(group_object)'.  The entire process is followed by a commit to Panorama.

## Context

I am currently able to work-around this issue by creating Address Groups individually using the .create() method.  This is not ideal as we are often creating hundreds of Address Groups at a time and this causes many API calls to Panorama which could be consolidated into a single bulk creation.  By the way, Address Objects which are created using the same bulk-creation .create_similar() method to be members of these Dynamic Address Groups do appear on the pick-list as a Source or Destination to be used in Security Pre-Rules whereas their Address Groups do not.

## Your Environment

-Python==3.8.5
-Panorama==PAN-OS 9.0.9
-pan-os-python==1.0.2

**Comment by btorresgil** [comment]
Hi @aaronmelton , thanks for reporting this issue. Since you say `create()` works but `create_similar()` doesn't, I can tell you the only difference between these methods is the typical size of the XML sent to the firewall. With `create()` the XML is small because it represents a single object/group. With `create_similar()` you're sending all the objects/groups at the same time in a larger XML string.

As you say, the XML is sent correctly because the groups show up in Panorama, and when you restart the management plane the groups show up in the pick list. So it sounds more like an issue in the API in your current PAN-OS/Panorama version, where it's unable to fully process the larger XML string in a single API call. I don't think this is an issue in the pan-os-python library.

I recommend to open an official Palo Alto Networks TAC case on this issue. That way our TAC team can analyze the problem and either provide a fixed version or report the issue to engineering to be fixed in PAN-OS/Panorama.

I'll go ahead and close this issue for now, but please feel free to re-open it if there's anything we can help with on the pan-os-python side of this issue. We're happy to take a deeper look as needed.
